os:
  - linux

language: python

install:
  - pip install --upgrade pip twine
  - pip install -r requirements-test.txt

jobs:
  include:
    - stage: test
      script:
        - pytest --cov=tir tests/
        - codecov
    - stage: deploy
      if: branch = master
      script:
        - python setup.py sdist bdist_wheel
        - twine upload dist/*
