language: python

python: "3.5"

install:
  - pip install --upgrade setuptools wheel pip
  - pip install -r requirements-test.txt
  - pip install twine

jobs:
  - stage: test
    python:
      - "3.5"
      - "3.6"
      - "3.7"
    script: codecov
  - stage: packaging
    script:
      - python setup.py sdist bdist_wheel
      - twine check dist/*
  - stage: deploy_test
    if: branch = develop
    script: twine upload --repository-url https://test.pypi.org/legacy/ dist/*;
  - stage: deploy
    if: branch = master
    script: twine upload dist/*;
