os:
  - linux

language: python

install:
  - pip install --upgrade pipenv pip codecov twine
  - pipenv install --dev

jobs:
  include:
    - stage: test
      script:
        - pytest --cov=tir tests/
        - codecov
    - stage: packaging
      script:
        - python setup.py sdist bdist_wheel
        - twine check dist/*
    - stage: Test package deployment
      if: branch = develop
      script:
        - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
    - stage: deploy
      if: branch = master
      script:
        - python setup.py sdist bdist_wheel
        - twine upload dist/*
