os:
  - linux

language: python

install:
  - pip install --upgrade pip codecov twine
  - pip install -r requirements-test.txt

jobs:
  include:
    - stage: test
      script:
        - pytest tests/
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      if: branch = master
      script:
        - python setup.py sdist bdist_wheel
        - twine upload dist/*
