version: 2.1
jobs:
  build:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          command: |
            sudo pip install virtualenv
            virtualenv venv
            
